import type { Product } from "../Types/Search/Product";
import OTHHOODIEGRAY from "../../../../Backend/src/Merch/OTH/OTH Hoodie grå.png";
import OCHOODIEBLACK  from "../../../../Backend/src/Merch/The OC/OC Hoodie svart.png";
import SKAMHOODIEWHITE from "../../../../Backend/src/Merch/Skam/Skam Hoodie vit.png";
import YRHOODIEBLACK  from "../../../../Backend/src/Merch/Young Royals/YRHoodie.png";
import OTHSWEATSHIRTBLACK from "../../../../Backend/src/Merch/OTH/OTH sweatshirt svart.png";
import OCSWEATSHIRTWHITE  from "../../../../Backend/src/Merch/The OC/OC Sweatshirt vit.png";
import SKAMSWEATSHIRTGRAY from "../../../../Backend/src/Merch/Skam/Skam Sweatshirt Grå.png";
import YRSWEATSHIRTBLACK from "../../../../Backend/src/Merch/Young Royals/YRsweatshirtsvart.png";
import OTHTSHIRTBLACK from "../../../../Backend/src/Merch/OTH/OTH tshirt dam svart.png";
import OCTSHIRTWHITE from "../../../../Backend/src/Merch/The OC/OC tshirt herr vit.png";
import SKAMTSHIRTGRAY from "../../../../Backend/src/Merch/Skam/SkamTshirtDamGrå.png";
import YRTSHIRTGRAY  from "../../../../Backend/src/Merch/Young Royals/YRtshirts.png";
import OCHOODIEWHITE from "../../../../Backend/src/Merch/The OC/OC Hoodie vit.png";
import { OTHSWEATSHIRTWHITE } from "./imgVariables";

const othClass = "othBlue";
const ocClass = "ocBeige";
const skamClass = "skamYellow";
const yrClass ="yrPurple"; 

export const products: Product[] = [
    {
        id: "91c20ef0-cf61-4ee1-a746-1ea1d6384244",
        label: "One Tree Hill Hoodie",
        fandom: "One Tree Hill",
        black: "",
        grey: OTHHOODIEGRAY,
        white: "",
        price: 20,
        path: "/:id",
        description: "This hoodie is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        class: othClass,
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        }
    },
    {
        id: "986a3e78-91c8-47b3-b5aa-fda66a776268",
        label: "The OC Hoodie",
        fandom: "The OC",
        black: OCHOODIEBLACK,
        white: OCHOODIEWHITE,
        grey:"",
        price: 20,
        path: "/The_OC_Hoodie",
        description: "This hoodie is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        class: ocClass,
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        }
    },
    {
        id: "d85407bf-400e-406f-bd13-26cc5fbf6e79",
        label: "Skam Hoodie",
        fandom: "Skam",
        white: SKAMHOODIEWHITE,
        grey: "",
        black: "",
        price: 20,
        path: "/Skam_Hoodie",
        description: "This hoodie is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        class: skamClass,
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        }
    },
    {
        id: "1adaaa10-c02b-493d-a7ce-027801551d40",
        label: "Young Royals Hoodie",
        fandom: "Young Royals",
        white: "",
        grey: "",
        black: YRHOODIEBLACK,
        price: 20,
        path: "/Young_Royals_Hoodie",
        description: "This hoodie is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        class: yrClass,
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        }
    },
    {
        id: "ded21a6c-ada4-4b1e-98c8-ce80f77638e4",
        label: "One Tree Hill Sweatshirt",
        fandom: "One Tree Hill",
        white: OTHSWEATSHIRTWHITE,
        grey: "",
        black: OTHSWEATSHIRTBLACK,
        price: 20,
        path: "OTH_Sweatshirt",
        description: "This sweatshirt is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        class: othClass,
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        },    
    },
    {
        id: "f2a0d44e-0de7-4272-803d-8037509eb87c",
        label: "The OC Sweatshirt",
        fandom: "The OC",
        white: OCSWEATSHIRTWHITE,
        grey: "",
        black: "",
        price: 20,
        path: "OC_Sweatshirt",
        description: "This sweatshirt is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        class: ocClass,
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        },    
    }, 
    {
        id: "bb010be2-899c-419e-a649-49dd441c9723",
        label: "Skam Sweatshirt",
        fandom: "Skam",
        white: "",
        grey: SKAMSWEATSHIRTGRAY,
        black: "",        
        price: 20,
        path: "Skam_Sweatshirt",
        description: "This sweatshirt is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        class: skamClass,
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        },    
    }, 
     {
        id: "a4d84529-a4fc-44aa-ae52-0e04e8f7d78f",
        label: "Young Royals Sweatshirt",
        fandom: "Young Royals",
        white: "",
        grey: "",
        black: YRSWEATSHIRTBLACK,
        price: 20,
        path: "Young_Royals_Sweatshirt",
        description: "This sweatshirt is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        class: yrClass,
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        },    
    }, 
    {
         id: "78657548-29e1-43b3-976e-d5b3fa24f276", 
         label: "One Tree Hill Tshirt", 
         fandom: "One Tree Hill", 
         white: "",
         grey: "",
         black: OTHTSHIRTBLACK, 
         price: 15, 
         path: "/OTH_Tshirt", 
         description: "This T-shirt is made from 100% premium cotton for a soft and breathable feel. The fabric ensures lasting comfort and durability, making it perfect for everyday wear.", 
         fit: "Regular",
         class: othClass,
         washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tuble dry low or hang to dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
         },
    },
    {
         id: "e970ae69-57da-4afa-a61b-312d450748be", 
         label: "The O.C Tshirt", 
         fandom: "The O.C", 
         white: OCTSHIRTWHITE, 
         grey: "",
         black: "",
         price: 15, 
         path: "/OC_Tshirt", 
         description: "This T-shirt is made from 100% premium cotton for a soft and breathable feel. The fabric ensures lasting comfort and durability, making it perfect for everyday wear.", 
         fit: "Regular",
         class: ocClass,
         washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tuble dry low or hang to dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
         },
    },
    {
         id: "f97a9dec-7aca-4a79-85d3-0901752eb7a4", 
         label: "Skam Tshirt", 
         fandom: "Skam", 
         white: "",
         grey: SKAMTSHIRTGRAY, 
         black: "",
         price: 15, 
         path: "/Skam_Tshirt", 
         description: "This T-shirt is made from 100% premium cotton for a soft and breathable feel. The fabric ensures lasting comfort and durability, making it perfect for everyday wear.", 
         fit: "Regular",
         class: skamClass,
         washing: {
            temp: 30,
            canBleach: false,
            similarColors: true,
            dry: "Tuble dry low or hang to dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
         },
    },
    {
         id: "0997addd-d7b1-4b47-bd5c-c740b33270ac", 
         label: "Young Royals Tshirt", 
         fandom: "Young Royals", 
         white: "",
         grey: YRTSHIRTGRAY, 
         black: "",
         price: 15, 
         path: "/Young_Royals_Tshirt", 
         description: "This T-shirt is made from 100% premium cotton for a soft and breathable feel. The fabric ensures lasting comfort and durability, making it perfect for everyday wear.", 
         fit: "Regular",
         class: yrClass,
         washing: {
            temp: 30,
            canBleach: false,
            similarColors: true,
            dry: "Tuble dry low or hang to dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
         },
    },
]