import type { Product } from "../types/Product";
import { OCSWEATSHIRT, OCTSHIRT, OTHHOODIE, OTHSWEATSHIRT, OTHTSHIRT, SKAMSWEATSHIRT, SKAMTSHIRT, YRSWEATSHIRT, YRTSHIRT } from "./imgVariables";
import { OCHOODIE } from "./imgVariables";
import { SKAMHOODIE } from "./imgVariables";
import { YRHOODIE } from "./imgVariables";

export const products: Product[] = [
    {
        id: "91c20ef0-cf61-4ee1-a746-1ea1d6384244",
        label: "One Tree Hill Hoodie",
        fandom: "One Tree Hill",
        imgUrl: OTHHOODIE,
        price: 20,
        path: "/OTH_Hoodie",
        description: "This hoodie is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        }
    },
    {
        id: "986a3e78-91c8-47b3-b5aa-fda66a776268",
        label: "The OC Hoodie",
        fandom: "The OC",
        imgUrl: OCHOODIE,
        price: 20,
        path: "/The_OC_Hoodie",
        description: "This hoodie is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        }
    },
    {
        id: "d85407bf-400e-406f-bd13-26cc5fbf6e79",
        label: "Skam Hoodie",
        fandom: "Skam",
        imgUrl: SKAMHOODIE,
        price: 20,
        path: "/Skam_Hoodie",
        description: "This hoodie is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        }
    },
    {
        id: "1adaaa10-c02b-493d-a7ce-027801551d40",
        label: "Young Royals Hoodie",
        fandom: "Young Royals",
        imgUrl: YRHOODIE,
        price: 20,
        path: "/Young_Royals_Hoodie",
        description: "This hoodie is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        }
    },
    {
        id: "ded21a6c-ada4-4b1e-98c8-ce80f77638e4",
        label: "One Tree Hill Sweatshirt",
        fandom: "One Tree Hill",
        imgUrl: OTHSWEATSHIRT,
        price: 20,
        path: "OTH_Sweatshirt",
        description: "This sweatshirt is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        },    
    },
    {
        id: "f2a0d44e-0de7-4272-803d-8037509eb87c",
        label: "The OC Sweatshirt",
        fandom: "The OC",
        imgUrl: OCSWEATSHIRT,
        price: 20,
        path: "OC_Sweatshirt",
        description: "This sweatshirt is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        },    
    }, 
    {
        id: "bb010be2-899c-419e-a649-49dd441c9723",
        label: "Skam Sweatshirt",
        fandom: "Skam",
        imgUrl: SKAMSWEATSHIRT,
        price: 20,
        path: "Skam_Sweatshirt",
        description: "This sweatshirt is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        },    
    }, 
     {
        id: "a4d84529-a4fc-44aa-ae52-0e04e8f7d78f",
        label: "Young Royals Sweatshirt",
        fandom: "Young Royals",
        imgUrl: YRSWEATSHIRT,
        price: 20,
        path: "Young_Royals_Sweatshirt",
        description: "This sweatshirt is made from a soft cotton and polyester blend that combines comfort, warmth, and durability. The brushed interior gives it a cozy feel, perfect for everyday wear or lounging.",
        fit: "Oversized",
        washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tumble dry or hang dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
        },    
    }, 
    {
         id: "78657548-29e1-43b3-976e-d5b3fa24f276", 
         label: "One Tree Hill Tshirt", 
         fandom: "One Tree Hill", 
         imgUrl: OTHTSHIRT, 
         price: 15, 
         path: "/OTH_Tshirt", 
         description: "This T-shirt is made from 100% premium cotton for a soft and breathable feel. The fabric ensures lasting comfort and durability, making it perfect for everyday wear.", 
         fit: "Regular",
         washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tuble dry low or hang to dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
         },
    },
    {
         id: "e970ae69-57da-4afa-a61b-312d450748be", 
         label: "The O.C Tshirt", 
         fandom: "The O.C", 
         imgUrl: OCTSHIRT, 
         price: 15, 
         path: "/OC_Tshirt", 
         description: "This T-shirt is made from 100% premium cotton for a soft and breathable feel. The fabric ensures lasting comfort and durability, making it perfect for everyday wear.", 
         fit: "Regular",
         washing: {
            temp: 30,
            similarColors: true,
            canBleach: false,
            dry: "Tuble dry low or hang to dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
         },
    },
    {
         id: "f97a9dec-7aca-4a79-85d3-0901752eb7a4", 
         label: "Skam Tshirt", 
         fandom: "Skam", 
         imgUrl: SKAMTSHIRT, 
         price: 15, 
         path: "/Skam_Tshirt", 
         description: "This T-shirt is made from 100% premium cotton for a soft and breathable feel. The fabric ensures lasting comfort and durability, making it perfect for everyday wear.", 
         fit: "Regular",
         washing: {
            temp: 30,
            canBleach: false,
            similarColors: true,
            dry: "Tuble dry low or hang to dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
         },
    },
    {
         id: "0997addd-d7b1-4b47-bd5c-c740b33270ac", 
         label: "Young Royals Tshirt", 
         fandom: "Young Royals", 
         imgUrl: YRTSHIRT, 
         price: 15, 
         path: "/Young_Royals_Tshirt", 
         description: "This T-shirt is made from 100% premium cotton for a soft and breathable feel. The fabric ensures lasting comfort and durability, making it perfect for everyday wear.", 
         fit: "Regular",
         washing: {
            temp: 30,
            canBleach: false,
            similarColors: true,
            dry: "Tuble dry low or hang to dry",
            iron: "Iron on low heat if needed (avoid print)",
            dryClean: false,
         },
    },
]